language: elixir
sudo: required
cache:
  directories:
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
elixir:
  - 1.4.2
otp_release:
  - 19.2
apt:
  packages:
    - inotify-tools
env:
  global:
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    # Docker Credentials
    - secure: "Vju4UNUVAtQty5WLBjBKFI9ZFB5NJJ1f5YOdgVzIsyAWLYk+Z0jXzGPphV+VI2RE3sU4hOETj3w6XKJBc1s2cVQMnKZse5n6IpImHhbDeL3pvNguoZHQm+HeSGo2YjyXzlyofvieFDHvT4C6amyyM+VRgpsLZhoWdwCxj23dMa1hIQXMPpZESoph1l26zjNDzNqkO3Zchd1JHkHor7jTNMAm+d31pgDuk8b4cw9Le1exBozreMFRgKYXCUHvQGlnAsjb/Ab9CR9+yfxVCz48l3z1OaZvpSKciSoeQKvgPoeeV17r1CgY0MnmBDIh4BHeVGPXkzjJoKOyWy/Znr2V0Su6H9XF4JzG8QqxW8YnPEISGEyvw2o1+150agZ2OiCBONYQO7sf6oekYazMYe4thA6HYHecvVLe4ANNYnp4Vgzg00uMsucO96/mbYcSOA7+0aaY3vPIaBk8zWm3EHN0dbbIqgtXBBfUaEL8pzHaq/9So0cMzgtZovX9CducrvQN7pvqH4+M05jXrWBJnT4F25UhE6yy6qk0YubRWWSkZQiji65qV3BEqtW7mCoyUefDVYqu+CCgNj6JaFwNjbSB0EEixIvCoi7aP5jdEsUwNk05h3EXS+is8A7zWN63dU4k4dXknpr2iAHsjKyfD6Zc1kBfoadF2gvDACi77+VS4JY="
    # GitHub Credentials
    - secure: "Yxg9Rh0O83SmaRbtRZVg/9bhBLfvCbDk2ZgwN+wXmUlOneCMNQ9ZXLeiAfUj03pAuMXskRCOnvG6Qajd1VOIhNWtvc8Gckp5T5dtUYlSDbHPQE0xsdfDHKNU6BISt0A7AkFF6U147ooH2/n73azbz58eeW0y0yfzMNdIf3Qpw6jUU6es6EAGW4RJI5HU+mE53E3VI97lVWOJD2r9auYk+0VeYccCBvVxyxePDZTr7wtuHxKgA4ZpJLsXbSazQjSHyxXumYyOX4L6m2i+fzOH6g0hBJc/9J8Gqvc1sIkNrDysW3g6m773l1S4bSfptF//5cAhg723s4tJyVhuDcwAmjjLnXcTXR01cXer4XfuCp6FNUu8ZHE3GIJ57MrxvU6mHCLIwZ9qtqmEepW/m+XwyVApf8PIt8R5aAOEQniAbBIcHanKEQZ3cG1vH7mvPOi8CvRA3HexsXk/i1e90oFMFp1GQnPX0g8D6GAZUqMbKkBr5NV90iAKwuuaOfmGyCfYS+uyzDZc+uZffnlEM4VkAWEH7+Nnhw+4kq0IMlhCT4nRdSuG3wAkuMDg75WZbVG4QxBFO5YGZivT9r91YT92DaCWwu39f/nUdZXcp4ZAyvT8E+PMpZmbjqJ0mb43qg7hGb9kzdXuDAvqP9Ngg9Gkx/4/bZbSuAWGtCmpCmXiSCE="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  # Expose MQ and DB to Docker container
  - sudo ./bin/ci/init-db.sh
script:
  # Increment version in mix.exs
  - ./bin/version-increment.sh
  # Install dependencies
  - mix deps.get
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - sudo ./bin/start.sh
  - sleep 5
  - docker ps
  - RUNNING_CONTAINERS=`docker ps | wc -l`;
  - if [ "${RUNNING_CONTAINERS//[[:space:]]/}" == "1" ]; then echo "[E] Container is not started\!"; docker logs mpi --details --since 5h; exit 1; fi;
  # Run acceptance tests on Docker container
  - "MIX_TEST_HOST=localhost MIX_TEST_PORT=4000 mix test test/acceptance"
after_failure:
  - docker logs mpi --details --since 5h
after_success:
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh
