language: elixir
sudo: required
cache:
  directories:
    - deps
services:
  - docker
  - postgresql
addons:
  postgresql: "9.5"
elixir:
  - 1.4.2
otp_release:
  - 19.2
notifications:
  slack: 
    rooms:
      - secure: "U9zov8EEr/rhmtZpNjXu0JB28wMLH49GnCXXw1RQJeStF5Z7z1GIyNSzeoa4IehQlQpGNxdpz9IQjE7lpIKSbBHnPiq2s+UH9UUD4K7EupqKqNVg0AirzFw60F0TdtIdQFO/ioeMYCrpxqHv6xTg8io7QEBSPu8A1iIIA5aMYMDaF8P72M0mJWUp+gONWT3MIE2oHGwKDka2VW1O/mihuD8UqlA13pqDMxqGA+KkVAJ104Uwq8Z9PY3OZMvi+sD8E8MTMjaEnp7X16oEFpAnqLvgjZgRhaXEYGO0NNMXGRT/n+fsLVVVAmQvReTsqaZ7fK9VyRpOvDAsv8rDwQd+6zEF8f7e13XKVTUIAJORaTWe2b3kVY+l3b20l/YzxnkXaxQ323Vf5vg++lbQHzkqXA1gVYl2AQlXndtN9ukYWmoSxv7y4VA2PjGzAMawZKNIP0/LTCkHX+uHJ1NpbpD7tXY2/wnsHu+T0+YRjEm9J8qJ19YHQ8H51OpSQ/hIApFwCG7aji9h8vpJ7v2bbU1YRe9iadn1hOc9a9xX5YKUC01S5mSJIvGt5sqO0TFSqwtNDxikwpXN8rb73fcZS5C36zyv23/6l/PkzvkKWQqXIhO8XPDXslpEHliQURBG2kv3Hmdj/roTq4Ew+tM/Yocpcj1xJdGT/qAkIvtJl9iXhQ4="
    on_success: always
apt:
  packages:
    - inotify-tools
env:
  global:
    - Chart=mpi
    - MIX_ENV=test
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
    - RELEASE_BRANCH="master"
    # Docker Credentials
    - secure: "lNSOl7jubWCk2H7lgiTE5iII0LziJ8SuTZtUsSIJxZV0RtLZUmf5c7HmEeXCG8quotX53k0Mw8FDPF+Y+NuBJ4sCmP9u8MLLWmRWgUwwNRzADwjekGvKOvEcaZURXK7asUvt+Vbsd1VcmFyUvh870jHIsbXhh5L8KpDXpjSXeH/x9HORr+TwMPHxpMWH40DGHjd46cjSaU1h9f2PwHwjukZNDthHdk0SCbuJl0rxfUNpOCy9bD5lZAgd8vB6QITUShgkJfy7fb5zEH51DdF5ZUsl+lB1Zrgxbu1kX32pzX1yVwKDEcJgqc1h93WKQzcHRu2E5h6nVe6PHvSOi4SadZ1O/4sjj7FrbYDvpwHt2Tzd8pur+x6uvOgag2VwwVYnl9fclayJ7x2fJI0a5LihQD92GmGFabV8aUxIB97Yl8GcJPWqrlgzkogwelzb2fcSRbsv/Nyhdvw4qrM7DURx3oDVMmrsZYvGGoyKOY8GnqlOmcEtDUoxabMdenzW6/dhirHU1y8u1SPY1dUmbuk7Zwu66uIok1K0xDpoP/FgKATVHq0KYWSZfrf7XuzEeB9lGq29YG4lBVnatmiRoeiNNdprxy+aa0AxS4TqycrI0A3onMT1pr05gcRkfduBSI4tiRuxiL5odko5Qogxv//4py7iL6Ln4F3X/hlr9R2lCBg="
    # GitHub Credentials
    - secure: "Pk7tFbHNfvJnjV5SJSRJcvra/fWHbFRBwaYDvMg+7HuAES0P6LKw6xk7n/VZpoX/cjc8fu/BExyaUIS0SjAZU43fS9/hK4+LnKFS5Eg42GozaL/qafuSYuCQgJXAPQZO/lvbcAPsMdeVWuLG3+YHhad5y4qjeqC5hLX1Ugs4gjqNE5GDYuu/Al1PQRGCmUs9WzN2GLflCzRgoqd73i4phabxhzQsHUG8j+Je2HU6ctyB2ZfUjkXbfcVMccNhf0NXMhGe1FpG7ZmtHCT9U3HlVrUyuJrHe2OnteCYkZ8CKbieamw9GXmPfj1toYui0w4TTVFo50N+riOGYGBAuZnMKqNV9E6Wwuqfm3DWzYZjc9hLb9j6uQNNI753xk2HNCzkgbmNuZU5pzY5Gf/xOt+Pi9fgYEyZLGvtUDJJ2qfBQmzksspht1eezrM8XCrgKxW7cSAXLtpzmaaqsT/d8v7GA9ZamnhWuMPS+qvK2Lcg91V6dY23JRWORTKXRvmR2Q827wFB52g3FvTL5U3YlJxlX3w/0naO7J3G2llxALvZkJNgJ+cvQws5K0u/LgrML3kCB7fBJfxLYktljL7WBzDpVY/1Tf/aZbLCaa5tGz6YM/CIfVyVHNuit5tf7yTmx2Y9jUKO7NlPuPfB48FdVYbTYo/XRuEG0Le9Eb6A+BBn2Ec="
branches:
  # Releases are generated automatically, stop infinite build loop
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - openssl aes-256-cbc -K $encrypted_df62b4135311_key -iv $encrypted_df62b4135311_iv -in eHealth-eef414faa06b.json.enc -out eHealth-eef414faa06b.json -d
  # Expose MQ and DB to Docker container
  - sudo ./bin/ci/init-db.sh
script:
  # Increment version in mix.exs
  - ./bin/version-increment.sh
  # Install dependencies
  - mix deps.get
  # Run all tests except pending ones
  - mix test --exclude pending --trace
  # Submit code coverage report to Coveralls
  # Add --pro if you using private repo.
  - mix coveralls.travis --exclude pending
  # Run static code analysis
  - mix credo --strict
  # Check code style
  - mix dogma
  # Build Docker container
  - ./bin/build.sh || travis_terminate 1
  # Initialize DB for Docker container
  - MIX_ENV=dev mix ecto.setup
  # Run Docker container
  - sudo ./bin/start.sh || travis_terminate 1
  # Run acceptance tests on Docker container
  - "MIX_TEST_HOST=localhost MIX_TEST_PORT=4000 mix test test/acceptance"
  # Submit Docker container to Docker Hub and create GitHub Release by pushing tag with changelog
  - ./bin/ci/push.sh || travis_terminate 1
  # CD to Dev
  - sudo ./bin/deploy.sh || travis_terminate 1
